before_install:
  - sudo apt-get update
install:
  - sudo apt-get install libqt4-dev python-qt4-dev
  - sudo pip install -r requirements.txt
script:
  - python qtSpectraViewer.py
language:
  - python
python:
  - "2.7"
