# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SettingsPanel.ui'
#
# Created: Fri Nov 02 00:31:53 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(582, 441)
        self.formLayoutWidget = QtGui.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 572, 401))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.defaultError = QtGui.QLineEdit(self.formLayoutWidget)
        self.defaultError.setObjectName(_fromUtf8("defaultError"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.defaultError)
        self.line = QtGui.QFrame(self.formLayoutWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.SpanningRole, self.line)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_3)
        self.aaBox = QtGui.QComboBox(self.formLayoutWidget)
        self.aaBox.setObjectName(_fromUtf8("aaBox"))
        self.aaBox.addItem(_fromUtf8(""))
        self.aaBox.addItem(_fromUtf8(""))
        self.aaBox.addItem(_fromUtf8(""))
        self.aaBox.addItem(_fromUtf8(""))
        self.aaBox.addItem(_fromUtf8(""))
        self.aaBox.addItem(_fromUtf8(""))
        self.aaBox.addItem(_fromUtf8(""))
        self.aaBox.addItem(_fromUtf8(""))
        self.aaBox.addItem(_fromUtf8(""))
        self.aaBox.addItem(_fromUtf8(""))
        self.aaBox.addItem(_fromUtf8(""))
        self.aaBox.addItem(_fromUtf8(""))
        self.aaBox.addItem(_fromUtf8(""))
        self.aaBox.addItem(_fromUtf8(""))
        self.aaBox.addItem(_fromUtf8(""))
        self.aaBox.addItem(_fromUtf8(""))
        self.aaBox.addItem(_fromUtf8(""))
        self.aaBox.addItem(_fromUtf8(""))
        self.aaBox.addItem(_fromUtf8(""))
        self.aaBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.aaBox)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_5)
        self.massLoss = QtGui.QLineEdit(self.formLayoutWidget)
        self.massLoss.setObjectName(_fromUtf8("massLoss"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.massLoss)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_6)
        self.displayName = QtGui.QLineEdit(self.formLayoutWidget)
        self.displayName.setObjectName(_fromUtf8("displayName"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.displayName)
        self.buttonBox = QtGui.QDialogButtonBox(self.formLayoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.buttonBox)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.SpanningRole, self.label_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.checkBoxa = QtGui.QCheckBox(self.formLayoutWidget)
        self.checkBoxa.setObjectName(_fromUtf8("checkBoxa"))
        self.horizontalLayout.addWidget(self.checkBoxa)
        self.checkBoxb = QtGui.QCheckBox(self.formLayoutWidget)
        self.checkBoxb.setObjectName(_fromUtf8("checkBoxb"))
        self.horizontalLayout.addWidget(self.checkBoxb)
        self.checkBoxc = QtGui.QCheckBox(self.formLayoutWidget)
        self.checkBoxc.setObjectName(_fromUtf8("checkBoxc"))
        self.horizontalLayout.addWidget(self.checkBoxc)
        self.checkBoxx = QtGui.QCheckBox(self.formLayoutWidget)
        self.checkBoxx.setObjectName(_fromUtf8("checkBoxx"))
        self.horizontalLayout.addWidget(self.checkBoxx)
        self.checkBoxy = QtGui.QCheckBox(self.formLayoutWidget)
        self.checkBoxy.setObjectName(_fromUtf8("checkBoxy"))
        self.horizontalLayout.addWidget(self.checkBoxy)
        self.checkBoxz = QtGui.QCheckBox(self.formLayoutWidget)
        self.checkBoxz.setObjectName(_fromUtf8("checkBoxz"))
        self.horizontalLayout.addWidget(self.checkBoxz)
        self.formLayout.setLayout(4, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.addLoss = QtGui.QPushButton(self.formLayoutWidget)
        self.addLoss.setObjectName(_fromUtf8("addLoss"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.addLoss)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Default Mass Error (ppm)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Amino Acid", None, QtGui.QApplication.UnicodeUTF8))
        self.aaBox.setItemText(0, QtGui.QApplication.translate("Dialog", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.aaBox.setItemText(1, QtGui.QApplication.translate("Dialog", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.aaBox.setItemText(2, QtGui.QApplication.translate("Dialog", "D", None, QtGui.QApplication.UnicodeUTF8))
        self.aaBox.setItemText(3, QtGui.QApplication.translate("Dialog", "E", None, QtGui.QApplication.UnicodeUTF8))
        self.aaBox.setItemText(4, QtGui.QApplication.translate("Dialog", "F", None, QtGui.QApplication.UnicodeUTF8))
        self.aaBox.setItemText(5, QtGui.QApplication.translate("Dialog", "G", None, QtGui.QApplication.UnicodeUTF8))
        self.aaBox.setItemText(6, QtGui.QApplication.translate("Dialog", "H", None, QtGui.QApplication.UnicodeUTF8))
        self.aaBox.setItemText(7, QtGui.QApplication.translate("Dialog", "I", None, QtGui.QApplication.UnicodeUTF8))
        self.aaBox.setItemText(8, QtGui.QApplication.translate("Dialog", "K", None, QtGui.QApplication.UnicodeUTF8))
        self.aaBox.setItemText(9, QtGui.QApplication.translate("Dialog", "L", None, QtGui.QApplication.UnicodeUTF8))
        self.aaBox.setItemText(10, QtGui.QApplication.translate("Dialog", "M", None, QtGui.QApplication.UnicodeUTF8))
        self.aaBox.setItemText(11, QtGui.QApplication.translate("Dialog", "N", None, QtGui.QApplication.UnicodeUTF8))
        self.aaBox.setItemText(12, QtGui.QApplication.translate("Dialog", "P", None, QtGui.QApplication.UnicodeUTF8))
        self.aaBox.setItemText(13, QtGui.QApplication.translate("Dialog", "Q", None, QtGui.QApplication.UnicodeUTF8))
        self.aaBox.setItemText(14, QtGui.QApplication.translate("Dialog", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.aaBox.setItemText(15, QtGui.QApplication.translate("Dialog", "S", None, QtGui.QApplication.UnicodeUTF8))
        self.aaBox.setItemText(16, QtGui.QApplication.translate("Dialog", "T", None, QtGui.QApplication.UnicodeUTF8))
        self.aaBox.setItemText(17, QtGui.QApplication.translate("Dialog", "V", None, QtGui.QApplication.UnicodeUTF8))
        self.aaBox.setItemText(18, QtGui.QApplication.translate("Dialog", "W", None, QtGui.QApplication.UnicodeUTF8))
        self.aaBox.setItemText(19, QtGui.QApplication.translate("Dialog", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Valid Fragmentations", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Mass Loss", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Display Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Custom Loss Masses", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxa.setText(QtGui.QApplication.translate("Dialog", "a", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxb.setText(QtGui.QApplication.translate("Dialog", "b", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxc.setText(QtGui.QApplication.translate("Dialog", "c", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxx.setText(QtGui.QApplication.translate("Dialog", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxy.setText(QtGui.QApplication.translate("Dialog", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxz.setText(QtGui.QApplication.translate("Dialog", "z", None, QtGui.QApplication.UnicodeUTF8))
        self.addLoss.setText(QtGui.QApplication.translate("Dialog", "Add Neutral Loss", None, QtGui.QApplication.UnicodeUTF8))

